package com.digitalpause.app.ui.theme

import androidx.compose.ui.graphics.Color

// DigitalPause Core Stitch Brand Palette
val IndigoPrimary = Color(0xFF4338CA)
val IndigoPrimaryDark = Color(0xFF818CF8)
val IndigoPrimaryFixed = Color(0xFFE3DFFF)
val IndigoOnPrimaryFixed = Color(0xFF100069)
val IndigoContainer = Color(0xFF4338CA)
val IndigoOnContainer = Color(0xFFC1BEFF)

// Mindful Balance (Teal)
val MindfulTeal = Color(0xFF0D9488)
val MindfulTealDark = Color(0xFF2DD4BF)
val MindfulTealContainer = Color(0xFFCCFBF1)
val MindfulTealOnContainer = Color(0xFF0F766E)
val MindfulTealFixed = Color(0xFF89F5E7)
val MindfulTealFixedDim = Color(0xFF6BD8CB)
val MindfulTealOnFixed = Color(0xFF00201D)

// Gentle Caution / Approaching Limit (Amber)
val GentleAmber = Color(0xFFD97706)
val GentleAmberDark = Color(0xFFFBBF24)
val GentleAmberContainer = Color(0xFF7D4200)
val GentleAmberOnContainer = Color(0xFFFFB477)
val GentleAmberFixed = Color(0xFFFFDCC3)
val GentleAmberFixedDim = Color(0xFFFFB77D)
val GentleAmberOnFixed = Color(0xFF2F1500)

// Rest Alert / Pause Intercept (Velvet Crimson)
val PauseCrimson = Color(0xFFE11D48)
val PauseCrimsonDark = Color(0xFFFB7185)
val PauseCrimsonContainer = Color(0xFFFFDAD6)
val PauseCrimsonOnContainer = Color(0xFF93000A)

// Neutral Slate Canvas (Light)
val CanvasLight = Color(0xFFF8F9FF)
val OnCanvasLight = Color(0xFF0B1C30)
val CanvasVariantLight = Color(0xFFD3E4FE)
val OnCanvasVariantLight = Color(0xFF464554)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFEFF4FF)
val SurfaceContainerBaseLight = Color(0xFFE5EEFF)
val SurfaceContainerHighLight = Color(0xFFDCE9FF)
val SurfaceContainerHighestLight = Color(0xFFD3E4FE)
val OutlineLight = Color(0xFF777586)
val OutlineVariantLight = Color(0xFFC7C4D7)

// Neutral Slate Canvas (Dark)
val CanvasDark = Color(0xFF0F172A)
val OnCanvasDark = Color(0xFFF8FAFC)
val CanvasVariantDark = Color(0xFF1E293B)
val OnCanvasVariantDark = Color(0xFF94A3B8)
val SurfaceContainerLowestDark = Color(0xFF0B1120)
val SurfaceContainerLowDark = Color(0xFF131D31)
val SurfaceContainerBaseDark = Color(0xFF1E293B)
val SurfaceContainerHighDark = Color(0xFF293548)
val SurfaceContainerHighestDark = Color(0xFF334155)
val OutlineDark = Color(0xFF64748B)
val OutlineVariantDark = Color(0xFF334155)
